# Generated by Django 4.2.6 on 2023-10-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0002_pasient'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasient',
            name='adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pasient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pasient',
            name='birthDate',
            field=models.DateField(null=True),
        ),
    ]
