# Generated by Django 4.2.6 on 2023-10-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0003_pasient_adress_pasient_age_pasient_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasient',
            name='age',
        ),
    ]
