# Generated by Django 4.2.6 on 2023-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blodtrykk', '0004_remove_pasient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasient',
            name='adress',
        ),
        migrations.AddField(
            model_name='pasient',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
